name: Build and Deploy Checkers PWA

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js in Version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Setup npm packages
        run: npm ci
      - name: Lint Code
        run: npm run lint --if-present
      - name: Build Code
        run: npm run build --if-present
      - name: Deploy to Github Page
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          git-config-name: Github Action
          commit-message: "Deployment from Job-Nr ${{ github.run_number }} triggered by Commit ${{ github.sha }}"
          branch: production
          folder: dist