name: Build and Deploy Checkers PWA

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js in Version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Lint and Build Code
        run: |
          npm ci
          npm run lint --if-present
          npm run build --if-present
      - name: Deploy to Github Page
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: production
          folder: dist